# Generated by Django 4.2 on 2023-05-15 18:22

import ckeditor.fields
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('nomAuteur', models.CharField(max_length=255)),
                ('article', ckeditor.fields.RichTextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('nomAuteur', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('video', models.FileField(null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('f_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temoignage.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('commentaire', ckeditor.fields.RichTextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('f_video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='temoignage.video')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('commentaire', ckeditor.fields.RichTextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('f_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='temoignage.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='f_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temoignage.categorie'),
        ),
    ]
