# Generated by Django 4.2 on 2023-05-16 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temoignage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.IntegerField()),
                ('video_f', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='temoignage.video')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.IntegerField()),
                ('article_f', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='play', to='temoignage.video')),
            ],
        ),
    ]
