# Generated by Django 4.2 on 2023-05-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temoignage', '0002_lecture_video_lecture_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture_video',
            name='machine_identifier',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='lecture_video',
            name='lecture',
            field=models.IntegerField(default=0),
        ),
    ]
