# Generated by Django 4.2 on 2023-05-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temoignage', '0003_lecture_video_machine_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture_video',
            name='video_f',
        ),
        migrations.DeleteModel(
            name='Lecture_Article',
        ),
        migrations.DeleteModel(
            name='Lecture_Video',
        ),
    ]
