# Generated by Django 4.2 on 2023-06-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temoignage', '0005_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnee',
            name='confirmation_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
