# Generated by Django 4.2 on 2023-06-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temoignage', '0006_abonnee_confirmation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnee',
            name='confirmation_token',
        ),
    ]
