# Generated by Django 4.2 on 2023-06-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temoignage', '0009_article_slug_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
