# Generated by Django 4.2 on 2023-06-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temoignage', '0010_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
