# Generated by Django 4.2 on 2023-06-20 16:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temoignage', '0011_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
